[book]
authors = ["Jiang Lan (姜蓝)"]
language = "en"
multilingual = false
src = "src"
title = "A Philosophy of Choice and Cost"

[output.html]
default-theme = "light"
additional-css = ["src/custom.css"]
